BasicBlogWebsite/Areas/Admin/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace BasicBlogWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BasicBlogWebsite/Areas/Admin/Controllers/SuggestionController.cs
using BasicBlogWebsite.Entity.Interfaces;
using BasicBlogWebsite.EntityViewModels;
using BasicBlogWebsite.Models;
using BasicBlogWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace BasicBlogWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SuggestionController : Controller
    {
        private readonly IMovieService _movieService;

        public SuggestionController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public IActionResult SuggestionIndex()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddSuggestion([FromBody] SuggestionViewModel m)
        {
            AlertContent alert = new AlertContent();
            if (ModelState.IsValid)
            {
                var suggestionAdd = await _movieService.AddSuggestion(m);
                return Json(suggestionAdd);

            }
            return Json(alert);
        }
        [HttpGet]
        public async Task<IActionResult> GetAll(int id)
        {
            var getsuggestion = await _movieService.GetAll(id);
            return Json(getsuggestion);
        }
        [HttpGet]
        public async Task<IActionResult> GetData(int id)
        {
            var getsuggestion = await _movieService.GetByIdAsync(id);
            return Json(getsuggestion);
        }
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
           var suggestion =  await _movieService.DeleteSuggestion(id);
            
            return Json(suggestion);
        }
        [HttpPost]
        public string UploadImage(int id, IFormFile file, [FromServices] IWebHostEnvironment webHostEnvironment)
        {
            if (file != null && file.Length > 0)
            {
                // wwwroot dizini içindeki Hakkında klasörünü oluştur
                var uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Oneriler");

                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                // Dosya adındaki türkçe karakterleri veya boşlukları kaldır
                var fileName = Path.GetFileNameWithoutExtension(file.FileName); // Uzantıyı dahil etmemek için FileNameWithoutExtension kullanılır
                fileName = RemoveTurkishCharactersAndSpaces(fileName); // Türkçe karakterleri ve boşlukları kaldıran fonksiyonu çağır
                var fileExtension = Path.GetExtension(file.FileName);
                fileName = fileName + fileExtension;

                var imagePath = Path.Combine(uploadsFolder, fileName);

                // Dosyayı kaydet
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                // Resmi yeniden boyutlandır
                var width = 1920; // İstediğiniz genişlik
                var height = 1280; // İstediğiniz yükseklik
                using (var image = Image.Load(imagePath))
                {
                    // İstenilen boyuta resmi yeniden boyutlandır
                    image.Mutate(x => x.Resize(new ResizeOptions
                    {
                        Size = new Size(width, height),
                        Mode = ResizeMode.Max
                    }));
                    // Yeniden boyutlandırılmış resmi kaydet
                    image.Save(imagePath);
                }

                return ("/Oneriler/" + fileName);
            }

            return null;
        }

        private string RemoveTurkishCharactersAndSpaces(string input)
        {
            // Türkçe karakterleri ve boşlukları kaldır
            string[] turkishChars = { "ç", "ğ", "ı", "i", "ö", "ş", "ü", " " };
            string[] replacementChars = { "c", "g", "i", "i", "o", "s", "u", "_" };

            for (int i = 0; i < turkishChars.Length; i++)
            {
                input = input.Replace(turkishChars[i], replacementChars[i]);
            }

            return input;
        }
    }
}

BasicBlogWebsite/Controllers/SuggestionController.cs
using BasicBlogWebsite.Entity.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BasicBlogWebsite.Controllers
{
   
    public class SuggestionController : Controller
    {
        private readonly  IMovieService _movieService;

        public SuggestionController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Movies(int id)
        {
            if (id==0)
            {
                id = 1;
            }
            var movies = await _movieService.GetPaginatedSuggestion(id,1);
            ViewBag.totalItem = movies.totalItems;
            ViewBag.pageNumber = id;
            return View(movies.Movies);
        }
        public async Task<IActionResult> MovieDetail(int id)
        {
            var movie = await _movieService.GetById(id);
            return View(movie);
        }
        public async Task<IActionResult> Games(int id)
        {
            if (id == 0)
            {
                id = 1;
            }
            var game = await _movieService.GetPaginatedSuggestion(id, 2);
            ViewBag.totalItem = game.totalItems;
            ViewBag.pageNumber = id;
            return View(game.Movies);
        }
        public async Task<IActionResult> GameDetail(int id)
        {
            var game = await _movieService.GetById(id);
            return View(game);
        }
        public async Task<IActionResult> Books(int id)
        {
            if (id == 0)
            {
                id = 1;
            }
            var game = await _movieService.GetPaginatedSuggestion(id, 3);
            ViewBag.totalItem = game.totalItems;
            ViewBag.pageNumber = id;
            return View(game.Movies);
        }
        public async Task<IActionResult> BookDetail(int id)
        {
            var game = await _movieService.GetById(id);
            return View(game);
        }
    }
}

BasicBlogWebsite/Views/Suggestion/BookDetail.cshtml
@model SuggestionViewModel
@{
    ViewData["Title"] = "BookDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }
</style>
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Kitap Detayları
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />
<div class="container mt-5">
    <div class="row">
        <!-- Film Görseli -->
        <div class="col-md-6">
            <img style="width:20rem;" src="@Model.SuggestionImage" alt="Movie Image" class="img-fluid">
        </div>
        <!-- Film Detayları -->
        <div class="col-md-6">
            <h3>@Model.SuggestionTitle</h3>
            @Html.Raw(Model.SuggestionDescription)
            <hr />
            @if (@Model.MovieUrl != null)
            {
                <p><a class="btn original-btn" href=@Model.MovieUrl>Fragman</a></p>
            }


        </div>
    </div>
</div>

BasicBlogWebsite/Views/Suggestion/Books.cshtml
@model List<SuggestionViewModel>
@{
    ViewData["Title"] = "Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }

    .card {
        transition: transform 0.3s;
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        }

            .card:hover .card-body {
                background-color: lightgray; /* Gri tonu, istediğiniz rengi kullanabilirsiniz */
            }
</style>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Kitap Önerileri
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <a asp-controller="Suggestion" asp-action="BookDetail" asp-route-id="@item.SuggestionId">
                <div class="col-md-4 mt-5">
                    <!-- 3 kart her satırda görünsün, bu yüzden col-md-4 kullandık -->
                    <div class="card" style="width: 18rem;">
                        <img src=@item.SuggestionImage class="card-img-top" alt="...">

                        <div class="card-body">
                            <h5 class="card-title">@item.SuggestionTitle</h5>
                            @if (item.SuggestionDescription.Length > 100)
                            {
                                <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription.Substring(0, 100) + "...")
                                </p>
                            }
                            else
                            {
                                <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription)
                                </p>
                            }
                            <a href="#" class="btn btn-primary">Detaylar</a>
                        </div>

                    </div>
                </div>
            </a>
        }
    </div>
    <div class="m-5">
        @if (ViewBag.totalItem > 0)
        {
            int totalPages = (int)Math.Ceiling((double)ViewBag.totalItem / 5); // Her sayfada 5 blog gönderisi olduğu varsayıldı
            int currentPage = ViewBag.pageNumber;

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <!-- Önceki sayfa butonu -->
                    <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="/movie/Index/@(currentPage - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    <!-- İlk sayfa -->
                    <li class="page-item @(currentPage == 1 ? "active" : "")">
                        <a class="page-link" href="/movie/Index/1">1</a>
                    </li>

                    <!-- Aradaki sayfalar (1 2 ... 7 8 ...) -->
                    @if (totalPages > 2)
                    {
                        if (currentPage > 3)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                        }

                        for (int i = Math.Max(2, currentPage - 2); i <= Math.Min(currentPage + 2, totalPages - 1); i++)
                        {
                            <li class="page-item @(currentPage == i ? "active" : "")">
                                <a class="page-link" href="/movie/Index/@i">@i</a>
                            </li>
                        }

                        if (currentPage < totalPages - 2)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                        }
                    }

                    <!-- Son sayfa -->
                    @if (totalPages > 1)
                    {
                        <li class="page-item @(currentPage == totalPages ? "active" : "")">
                            <a class="page-link" href="/movie/Index/@totalPages">@totalPages</a>
                        </li>
                    }

                    <!-- Sonraki sayfa butonu -->
                    <li class="page-item @(currentPage == totalPages ? "disabled" : "")">
                        <a class="page-link" href="/movie/Index/@(currentPage + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        }
    </div>
</div>

BasicBlogWebsite/Views/Suggestion/GameDetail.cshtml
@model SuggestionViewModel
@{
    ViewData["Title"] = "GameDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }
</style>
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Oyun Detayları
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />
<div class="container mt-5">
    <div class="row">
        <!-- Film Görseli -->
        <div class="col-md-6">
            <img style="width:20rem;" src="@Model.SuggestionImage" alt="Movie Image" class="img-fluid">
        </div>
        <!-- Film Detayları -->
        <div class="col-md-6">
            <h3>@Model.SuggestionTitle</h3>
            @Html.Raw(Model.SuggestionDescription)
            <hr />
            @if ( @Model.MovieUrl!=null)
            {
                <p><a class="btn original-btn" href=@Model.MovieUrl>Fragman</a></p>
            }
           

        </div>
    </div>
</div>

BasicBlogWebsite/Views/Suggestion/Games.cshtml
@model List<SuggestionViewModel>
@{
    ViewData["Title"] = "Games";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }

    .card {
        transition: transform 0.3s;
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        }

            .card:hover .card-body {
                background-color: lightgray; /* Gri tonu, istediğiniz rengi kullanabilirsiniz */
            }
</style>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Oyun Önerileri
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <a asp-controller="Suggestion" asp-action="GameDetail" asp-route-id="@item.SuggestionId">
                <div class="col-md-4 mt-5">
                    <!-- 3 kart her satırda görünsün, bu yüzden col-md-4 kullandık -->
                    <div class="card" style="width: 18rem;">
                        <img src=@item.SuggestionImage class="card-img-top" alt="...">

                        <div class="card-body">
                            <h5 class="card-title">@item.SuggestionTitle</h5>
                            @if (item.SuggestionDescription.Length > 100)
                            {
                                <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription.Substring(0, 100) + "...")
                                </p>
                            }
                            else
                            {
                                <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription)
                                </p>
                            }
                            <a href="#" class="btn btn-primary">Detaylar</a>
                        </div>

                    </div>
                </div>
            </a>
        }
    </div>
    <div class="m-5">
        @if (ViewBag.totalItem > 0)
        {
            int totalPages = (int)Math.Ceiling((double)ViewBag.totalItem / 5); // Her sayfada 5 blog gönderisi olduğu varsayıldı
            int currentPage = ViewBag.pageNumber;

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <!-- Önceki sayfa butonu -->
                    <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="/movie/Index/@(currentPage - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    <!-- İlk sayfa -->
                    <li class="page-item @(currentPage == 1 ? "active" : "")">
                        <a class="page-link" href="/movie/Index/1">1</a>
                    </li>

                    <!-- Aradaki sayfalar (1 2 ... 7 8 ...) -->
                    @if (totalPages > 2)
                    {
                        if (currentPage > 3)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                        }

                        for (int i = Math.Max(2, currentPage - 2); i <= Math.Min(currentPage + 2, totalPages - 1); i++)
                        {
                            <li class="page-item @(currentPage == i ? "active" : "")">
                                <a class="page-link" href="/movie/Index/@i">@i</a>
                            </li>
                        }

                        if (currentPage < totalPages - 2)
                        {
                            <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                        }
                    }

                    <!-- Son sayfa -->
                    @if (totalPages > 1)
                    {
                        <li class="page-item @(currentPage == totalPages ? "active" : "")">
                            <a class="page-link" href="/movie/Index/@totalPages">@totalPages</a>
                        </li>
                    }

                    <!-- Sonraki sayfa butonu -->
                    <li class="page-item @(currentPage == totalPages ? "disabled" : "")">
                        <a class="page-link" href="/movie/Index/@(currentPage + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        }
    </div>
</div>

BasicBlogWebsite/Views/Suggestion/MovieDetail.cshtml
@model SuggestionViewModel
@{
    ViewData["Title"] = "MovieDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
}
<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }
</style>
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Film Detayları
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />
<div class="container mt-5">
    <div class="row">
        <!-- Film Görseli -->
        <div class="col-md-6">
            <img style="width:20rem;" src="@Model.SuggestionImage" alt="Movie Image" class="img-fluid">
        </div>
        <!-- Film Detayları -->
        <div class="col-md-6">
            <h3>@Model.SuggestionTitle</h3>
            @Html.Raw(Model.SuggestionDescription)
   <hr />
            <p><a class="btn original-btn" href=@Model.MovieUrl>Fragman</a></p>
         
        </div>
    </div>
</div>

BasicBlogWebsite/Views/Suggestion/Movies.cshtml
@model List<SuggestionViewModel>
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .hakkinda {
        font-size: 3rem;
        text-align: center;
        color: beige;
        font-family: emoji;
    }

    .card {
        transition: transform 0.3s;
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            background-color: rgba(255, 69, 0, 0.60);

        }

            .card:hover img {
                opacity: 0.5; 
            }
           /*  .card:hover .card-body {
                background-color: lightgray; /* Gri tonu, istediğiniz rengi kullanabilirsiniz */
           
            }
 */
   
</style>
<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-color:lightslategray">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div>
                    <h2 class="hakkinda">
                        Film Önerileri
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <a asp-controller="Suggestion" asp-action="MovieDetail" asp-route-id="@item.SuggestionId">
            <div class="col-md-4 mt-5">
                <!-- 3 kart her satırda görünsün, bu yüzden col-md-4 kullandık -->
                <div class="card" style="width: 18rem; border-radius:15px;">
                        <img src=@item.SuggestionImage class="card-img-top" style="border-top-left-radius:15px; border-top-right-radius:15px;" alt="...">
                    
                    <div class="card-body">
                        <h5 class="card-title">@item.SuggestionTitle</h5>
                        @if (item.SuggestionDescription.Length > 100)
                        {
                            <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription.Substring(0, 100) + "...")
                            </p>
                        }
                        else
                        {
                            <p class="card-text">
                                    @Html.Raw(item.SuggestionDescription)
                            </p>
                        }
                        <a href="#" class="btn btn-primary">Detaylar</a>
                    </div>
                   
                </div>
            </div>
            </a>
        }
    </div>
    <div class="m-5">
    @if (ViewBag.totalItem > 0)
    {
        int totalPages = (int)Math.Ceiling((double)ViewBag.totalItem / 5); // Her sayfada 5 blog gönderisi olduğu varsayıldı
        int currentPage = ViewBag.pageNumber;

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <!-- Önceki sayfa butonu -->
                <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                    <a class="page-link" href="/movie/Index/@(currentPage - 1)" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                <!-- İlk sayfa -->
                <li class="page-item @(currentPage == 1 ? "active" : "")">
                        <a class="page-link" href="/movie/Index/1">1</a>
                </li>

                <!-- Aradaki sayfalar (1 2 ... 7 8 ...) -->
                @if (totalPages > 2)
                {
                    if (currentPage > 3)
                    {
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    }

                    for (int i = Math.Max(2, currentPage - 2); i <= Math.Min(currentPage + 2, totalPages - 1); i++)
                    {
                        <li class="page-item @(currentPage == i ? "active" : "")">
                                <a class="page-link" href="/movie/Index/@i">@i</a>
                        </li>
                    }

                    if (currentPage < totalPages - 2)
                    {
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    }
                }

                <!-- Son sayfa -->
                @if (totalPages > 1)
                {
                    <li class="page-item @(currentPage == totalPages ? "active" : "")">
                            <a class="page-link" href="/movie/Index/@totalPages">@totalPages</a>
                    </li>
                }

                <!-- Sonraki sayfa butonu -->
                <li class="page-item @(currentPage == totalPages ? "disabled" : "")">
                        <a class="page-link" href="/movie/Index/@(currentPage + 1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    }
    </div>
</div>